version: '3'

services:
  client:
    build: ./client
    ports:
      - "3001:3001"
    depends_on:
      - payload
    environment:
      API_URI: http://payload:3000
  payload:
    build: ./admin
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: development
      PAYLOAD_SECRET: TESTING
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
volumes:
  data: